server:
  port: 8080

## SPRING
spring:
  application:
    name: businessinfo

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bussiness_info?useSSL=true&verifyServerCertificate=false&useUnicode=true&character_set_server=utf8mb4
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 10
