server:
  port: 8080

## SPRING
spring:
  application:
    name: onboarding

  datasource:
    url: jdbc:mysql://13.76.172.160:3306/enterprise?useSSL=true&verifyServerCertificate=false&useUnicode=true&character_set_server=utf8mb4
    username: hisalon@hisalon-dev
    password: Mbinno!@#456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 10
